* During commandline parsing invalid options are checked for. * Removed the "-x" debugging option that was accidently left on during last commit.

diff --git a/iscp b/iscp
--- a/iscp
+++ b/iscp
@@ -1,4 +1,4 @@
-#!/bin/bash -x
+#!/bin/bash
 #iscp
 # Copyright (C) 2009 Daniel Liew
 #
@@ -589,6 +589,12 @@ for ((i=1; i<=$#; i++)); do
 	if [ "${!i}" == "--retry" ]; then 
 		ISCP_RETRY=1; 
 		continue; 
+	fi
+
+	#check for invalid options
+	if [ $(echo "${!i}" | grep -Eci '^--') -eq 1 ]; then
+		echo "Error: Option ${!i} is not supported. Use --help to see available options." 1>&2
+		exit 1;
 	fi
 	
 	#check for sourcedir and target dir arguments
